### ISSUE TITLE
외부 API를 라우터 핸들러로 쓰는 법

### ISSUE THREAD

**Issue by RAINBOWJYP** [GraduationGoodBye/Frontend#3]
라우터 핸들러로 외부 API쓸 때 route.ts안에서 또 외부 API로 fetch해주는거 맞나요??

```typescript
//features/login/api/route.ts
export async function GET() {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/members/signup/google`,
  );
  const data = await res.json();

  return Response.json({ data });
}

```

```typescript
// features/login/ui/LoginButton.tsx
// 'use client'
const data = getLoginStatus()
  const getLoginStatus = async () => {
    await fetch("/features/login/api");
  };
```

**Comment by mahwin** [comment]
넥스트 서버에서 api를 핸들링하기 쉽게 만든게 라우터 핸들러네요.

외부 API로 fetch 하는 작업은 흔한 작업일 것 같고, 저렇게 사용할 것 같습니다.

질문 : 
1. app 디렉토리에 포함되지 않아도 동작을 하나요 ?
2. 라우터 핸들러를 사용한다고 가정하면 모든 api를 라우터 핸들러로 다루나요 ?
- 어떤 건 바로 fetch하고, 어떤건 라우터 핸들러 사용하고 한다면 어지러워 보여서 물어봅니다.

**Comment by tptkds** [comment]
signup이 아니라 signin 아닌가요?

그리고 응답으로 리디렉션이 올텐데 json이 아니라 Response.redirect(res.url);처럼 리디렉션 url을 클라이언트로 반환해 주는 게 맞는 거 같아요!

**Comment by tptkds** [comment]
그리고 유석님 코멘트처럼 app/api 하위에 넣어주셔야 라우트 핸들러로서 동작합니다!

**Comment by tptkds** [comment]
> 넥스트 서버에서 api를 핸들링하기 쉽게 만든게 라우터 핸들러네요.
> 
> 외부 API로 fetch 하는 작업은 흔한 작업일 것 같고, 저렇게 사용할 것 같습니다.
> 
> 질문 :
> 
> 1. app 디렉토리에 포함되지 않아도 동작을 하나요 ?
> 2. 라우터 핸들러를 사용한다고 가정하면 모든 api를 라우터 핸들러로 �다루나요 ?
> 
> * 어떤 건 바로 fetch하고, 어떤건 라우터 핸들러 사용하고 한다면 �어지러워 보여서 물어봅니다.

얼마 전 까지는 개인적으로 모든 api를 라우트핸들러로 다뤘었는데요. 이제는 외부에서 접근하는 next 서버 엔드포인트가 필요하지 않는 이상 관심사 분리의 이유로 서버 컴포넌트에서 api를 다루기로 했습니다..! 

CORS에러가 서비스 서버에서 설정을 통해 해결된다면 라우트 핸들러를 사용하지 않고 컴포넌트에서 api 요청해 주시는 게 맞습니다.
해결이 되지 않는다면 클라이언트에서 해결해야 하는데, next.js 라우트 핸들러를 통해 리디렉션하면 CORS에러가 해결된 경우가 있었거든요.

그래서 해나님에게 CORS에러가 서버 측에서 해결이 안 된 다면 그렇게 한 번 해 보시라고 말씀드렸었어요~!
